### ISSUE TITLE
Liquid Asset view crash trying to click a bar for 2nd time

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#88]
Repro steps:
- Click one bar.
- slide back
- click another graph

App stops with the following stack trace:

```
07-21 10:30:41.385: E/AndroidRuntime(3798): FATAL EXCEPTION: main
07-21 10:30:41.385: E/AndroidRuntime(3798): Process: org.missionassetfund.apps.android, PID: 3798
07-21 10:30:41.385: E/AndroidRuntime(3798): java.lang.NullPointerException
07-21 10:30:41.385: E/AndroidRuntime(3798):   at org.missionassetfund.apps.android.fragments.DailyTransactionsDetailChartFragment.setupChart(DailyTransactionsDetailChartFragment.java:48)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at org.missionassetfund.apps.android.fragments.DailyTransactionsDetailChartFragment.onCreateView(DailyTransactionsDetailChartFragment.java:33)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:550)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:509)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:908)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2819)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment.goToNextChart(LiquidAssetsFragment.java:213)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at org.missionassetfund.apps.android.activities.LiquidAssetsActivity.onBarClicked(LiquidAssetsActivity.java:25)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at org.missionassetfund.apps.android.fragments.DailyTransactionsChartFragment$1.onClick(DailyTransactionsChartFragment.java:49)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at com.echo.holographlibrary.BarGraph.onTouchEvent(BarGraph.java:407)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.View.dispatchTouchEvent(View.java:7736)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.app.Activity.dispatchTouchEvent(Activity.java:2466)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.View.dispatchPointerEvent(View.java:7916)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4023)
07-21 10:30:41.385: E/AndroidRuntime(3798):   at android.view.ViewRootImpl$ViewPostImeInput
```

**Comment by fcduarte** [comment]
Fixed by #86
