### ISSUE TITLE
Getting IndexOutOfBoundsException on Transaction View when the user has no transaction

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#90]
Testing for new user flow. Transaction View crashes when there are no transactions:

```
07-21 15:48:33.733: E/AndroidRuntime(26937): FATAL EXCEPTION: main
07-21 15:48:33.733: E/AndroidRuntime(26937): Process: org.missionassetfund.apps.android, PID: 26937
07-21 15:48:33.733: E/AndroidRuntime(26937): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
07-21 15:48:33.733: E/AndroidRuntime(26937):  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at java.util.ArrayList.get(ArrayList.java:308)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment.setupChart(LiquidAssetsFragment.java:197)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment.access$2(LiquidAssetsFragment.java:194)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment$1.done(LiquidAssetsFragment.java:99)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at com.parse.FindCallback.internalDone(FindCallback.java:45)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at com.parse.FindCallback.internalDone(FindCallback.java:31)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at com.parse.Parse$5$1.run(Parse.java:891)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at android.os.Handler.handleCallback(Handler.java:733)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at android.os.Handler.dispatchMessage(Handler.java:95)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at android.os.Looper.loop(Looper.java:136)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at android.app.ActivityThread.main(ActivityThread.java:5086)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at java.lang.reflect.Method.invokeNative(Native Method)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at java.lang.reflect.Method.invoke(Method.java:515)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-21 15:48:33.733: E/AndroidRuntime(26937):  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by fcduarte** [comment]
@josemontesdeoca do you have the latest code? it's strange because line 197 points to a method:

https://github.com/CodePath-MAF/AndroidClient/blob/master/src/org/missionassetfund/apps/android/fragments/LiquidAssetsFragment.java#L197

But I get the first group to create the graph (line 200) so the IOBE could be there .. Will take a look when I have some time, I didn't test using a fresh user -- shame on me :)

**Comment by josemontesdeoca** [comment]
no worries. let me test this with master latest :) and report back.

**Comment by fcduarte** [comment]
@josemontesdeoca anyway, thanks for the hard work of testing and pointing out those problems!

**Comment by josemontesdeoca** [comment]
Tested with master. having the same trouble. here is the new stacktrace:

```
07-21 16:15:09.536: E/AndroidRuntime(29983): FATAL EXCEPTION: main
07-21 16:15:09.536: E/AndroidRuntime(29983): Process: org.missionassetfund.apps.android, PID: 29983
07-21 16:15:09.536: E/AndroidRuntime(29983): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
07-21 16:15:09.536: E/AndroidRuntime(29983):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at java.util.ArrayList.get(ArrayList.java:308)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment.setupChart(LiquidAssetsFragment.java:200)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment.access$2(LiquidAssetsFragment.java:197)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at org.missionassetfund.apps.android.fragments.LiquidAssetsFragment$1.done(LiquidAssetsFragment.java:99)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at com.parse.FindCallback.internalDone(FindCallback.java:45)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at com.parse.FindCallback.internalDone(FindCallback.java:31)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at com.parse.Parse$5$1.run(Parse.java:891)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at android.os.Handler.handleCallback(Handler.java:733)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at android.os.Handler.dispatchMessage(Handler.java:95)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at android.os.Looper.loop(Looper.java:136)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at android.app.ActivityThread.main(ActivityThread.java:5086)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at java.lang.reflect.Method.invokeNative(Native Method)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at java.lang.reflect.Method.invoke(Method.java:515)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-21 16:15:09.536: E/AndroidRuntime(29983):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by josemontesdeoca** [comment]
@fcduarte you are more than welcome! appreciate the message. Trying to get the app ready for demo :) so I hope this issues are found useful not any other way around.

**Comment by fcduarte** [comment]
@josemontesdeoca will we start the demo with a fresh user?

**Comment by josemontesdeoca** [comment]
@fcduarte the first part of the demo relies on a new user flow (Set up initial balance). Tt would be nice if it did not had any transactions at that point.

For the 2nd part of the demo, we might want a user that has more activities to show a nicer Transaction view.

**Comment by fcduarte** [comment]
Fixed.
